export const courseMetadata: Record<string, { emoji: string }> = {
    // Accounting and Finance
    "Finance": { emoji: "💹" },
    "Accounting": { emoji: "📒" },
    "Accounting and Finance": { emoji: "🧾" },
    "Banking and Finance": { emoji: "🏦" },
    "Economics and Finance": { emoji: "📈" },
    "Islamic Finance": { emoji: "🕌" },
    "Professional Accounting": { emoji: "🧑‍💼" },

    // Architecture and Built Environment
    "Architecture": { emoji: "🏛️" },
    "Construction Management": { emoji: "🚧" },
    "Interior Architecture": { emoji: "🛋️" },
    "Interior Design": { emoji: "🖼️" },
    "Quantity Surveying": { emoji: "📏" },
    "Urban Planning": { emoji: "🏙️" },

    // Business
    "Management": { emoji: "👔" },
    "Actuarial Science": { emoji: "📊" },
    "Business Administration": { emoji: "🗂️" },
    "Business and Management": { emoji: "🏢" },
    "Economics": { emoji: "💵" },
    "Entrepreneurship": { emoji: "🚀" },
    "Human Resource Management": { emoji: "🧑‍🤝‍🧑" },
    "International Business": { emoji: "🌐" },
    "Logistics and Supply Chain Management": { emoji: "🚚" },
    "Marketing": { emoji: "📢" },
    "MBA Programme": { emoji: "🎓" },
    "Project Management": { emoji: "🗃️" },
    "Property & Real Estate": { emoji: "🏘️" },
    "Retail Management": { emoji: "🛒" },

    // Communication and Media Studies
    "Animation": { emoji: "🎞️" },
    "Broadcasting": { emoji: "📻" },
    "Communication": { emoji: "🗣️" },
    "Film & Television": { emoji: "📺" },
    "Graphic Design": { emoji: "🎨" },
    "Journalism": { emoji: "📰" },
    "Mass Communication": { emoji: "📡" },
    "Multimedia Design": { emoji: "🖥️" },

    // Computing and IT
    "Computer Science": { emoji: "💻" },
    "Information Systems": { emoji: "🗃️" },
    "Information Technology (IT)": { emoji: "🖱️" },
    "Software Engineering": { emoji: "🧑‍💻" },

    // Creative Arts and Design
    "Creative Arts": { emoji: "🎭" },
    "Fashion Design": { emoji: "👗" },
    "Industrial Design": { emoji: "🏭" },
    "Make-Up and Hair Design": { emoji: "💄" },
    "Music": { emoji: "🎵" },
    "Performing Arts": { emoji: "🎤" },

    // Education
    "Education": { emoji: "🍎" },
    "Early Childhood Education": { emoji: "🧸" },
    "English (Teaching)": { emoji: "📚" },
    "Special Needs Education": { emoji: "🧩" },
    "Teaching": { emoji: "👩‍🏫" },

    // Engineering
    "Electronic Engineering": { emoji: "🔌" },
    "Aeronautical Engineering": { emoji: "✈️" },
    "Aircraft Maintenance Engineering": { emoji: "🛠️" },
    "Automotive Technology": { emoji: "🚗" },
    "Biomedical Engineering": { emoji: "🧬" },
    "Chemical Engineering": { emoji: "⚗️" },
    "Civil Engineering": { emoji: "🏗️" },
    "Computer Systems Engineering": { emoji: "💾" },
    "Electrical & Electronic Engineering": { emoji: "💡" },
    "Electrical Engineering": { emoji: "⚡" },
    "General Engineering and Technology": { emoji: "🛠️" },
    "Industrial Engineering": { emoji: "🧑‍🏭" },
    "Manufacturing Engineering": { emoji: "🏭" },
    "Mechanical Engineering": { emoji: "⚙️" },
    "Mechatronics Engineering": { emoji: "🤖" },
    "Petroleum Engineering": { emoji: "🛢️" },
    "Geomatic Engineering": { emoji: "🗺️" },
    "Material Engineering": { emoji: "🧱" },

    // Hospitality and Services
    "Tourism Management": { emoji: "🧳" },
    "Culinary Arts": { emoji: "🍳" },
    "Event Management": { emoji: "🎪" },
    "Hospitality and Tourism Management": { emoji: "🏨" },
    "Hospitality Management": { emoji: "🛎️" },
    "Hotel Management": { emoji: "🏩" },

    // International Pre-University
    "American Degree Transfer Programme": { emoji: "🇺🇸" },
    "Australian Degree Transfer Programme": { emoji: "🇦🇺" },
    "Australian Matriculation (AUSMAT)": { emoji: "🦘" },
    "Canadian Matriculation": { emoji: "🇨🇦" },
    "A-Level": { emoji: "🅰️" },
    "Monash University Foundation Year (MUFY)": { emoji: "🇦🇺" },
    "South Australian Certificate of Education (SACE)": { emoji: "🦘" },
    "Transition Program": { emoji: "🔄" },
    "International Baccalaureate (IB)": { emoji: "🧑‍🎓" },
    "International Baccalaureate (IB Diploma)": { emoji: "🧑‍🎓" },

    // Language and Social Studies
    "English": { emoji: "🇬🇧" },
    "Counselling": { emoji: "🗨️" },
    "Chinese Studies": { emoji: "🀄" },
    "Malay Studies": { emoji: "🇲🇾" },
    "Policy Science": { emoji: "📜" },
    "International Relations": { emoji: "🤝" },
    "Psychology": { emoji: "🧠" },
    "Social Sciences": { emoji: "🧑‍🤝‍🧑" },
    "Translation Studies": { emoji: "🔤" },
    "Police Science": { emoji: "👮" },
    "Language Studies": { emoji: "🗣️" },

    // Law
    "Certificate in Legal Practice (CLP)": { emoji: "🧑‍⚖️" },
    "Law (LL.B.)": { emoji: "⚖️" },
    "UK Law Degree Transfer Programme": { emoji: "🇬🇧" },

    // Medicine and Allied Health Sciences
    "Chiropractic": { emoji: "💆" },
    "Dentistry": { emoji: "🦷" },
    "Health Studies": { emoji: "🏥" },
    "Healthcare": { emoji: "🩺" },
    "Medical Sciences": { emoji: "🧬" },
    "Medical Technology": { emoji: "🧪" },
    "Medicine": { emoji: "🩺" },
    "Nursing": { emoji: "👩‍⚕️" },
    "Nutrition": { emoji: "🥗" },
    "Occupational Safety & Health": { emoji: "🦺" },
    "Optometry": { emoji: "👓" },
    "Pharmaceutical Science": { emoji: "💊" },
    "Pharmacy": { emoji: "🏪" },
    "Physiotherapy": { emoji: "🏃‍♂️" },
    "Sports Science": { emoji: "🏅" },
    "Traditional Chinese Medicine": { emoji: "🌿" },
    "Veterinary Medicine": { emoji: "🐾" },
    "Biomedical Sciences": { emoji: "🧬" },
    "Forensic Science": { emoji: "🕵️‍♂️" },

    // Science and Mathematics
    "Chemistry": { emoji: "🧪" },
    "Agriculture": { emoji: "🌾" },
    "Aquatic Science": { emoji: "🐟" },
    "Biochemistry": { emoji: "🧫" },
    "Bioinformatics": { emoji: "🧬" },
    "Biology": { emoji: "🦠" },
    "Biotechnology": { emoji: "🧬" },
    "Environmental Health": { emoji: "🌱" },
    "Environmental Sciences": { emoji: "🌍" },
    "Food Science": { emoji: "🍎" },
    "General Sciences (Postgraduate)": { emoji: "🧑‍🔬" },
    "Geology": { emoji: "🪨" },
    "Mathematics": { emoji: "➗" },
    "Physics": { emoji: "🧲" },
    "Geography": { emoji: "🗺️" },
    "General Sciences (Oversea)": { emoji: "🌏" },
    "Nautical Science": { emoji: "⚓" },
}